syntax on
filetype plugin on

set nocompatible
set relativenumber
set laststatus=2
set wrap
set complete=.,w,b,u,t,i,kspell
set hlsearch
set incsearch
set clipboard=innamedplus
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set fileformat=unix
set encoding =utf-8
set wildmode=longest,list,full
set cursorline
:highlight Cursorline cterm=bold ctermbg=black
set ignorecase
set smartcase
set showmatch
autocmd BufWritePre *.py :%s/\s\+$//e
autocmd BufWritePre *.f90 :%s/\s\+$//e
autocmd BufWritePre *.f95 :%s/\s\+$//e
autocmd BufWritePre *.for :%s/\s\+$//e

" Nerdtree remap
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>


" Call the .vim.plug file
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

