- hosts: localhost
  connection: local
  become: true
  
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        state: latest
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - lsb-release
          - gnupg-agent
      changed_when: False
 
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/dot-files.yml
    - include: tasks/packages-files.yml

