- hosts: localhost
  connection: local
  become: true
  pre_tasks:

    - name: Add Docker GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filenme: docker

    - name: Add Google Cloud SDK GPG Key
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Google Cloud repository 
      apt_repository:
        repo: dep https://packages.cloud.google.com/apt cloud-sdk main 
        state: present

    - name: Add Google Chrome SDK GPG Key
      become: true
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome

    - name: Add Golang PPA 
      apt_repository:
        repo: ppa:longsleep/golang-backports
        state: present

    - name: update repositories
      apt:
        update_cache: yes
        state: latest
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - lsb-release
          - gnupg-agent
          - python3-pip
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/dot-files.yml
    - include: tasks/packages-files.yml
    - include: tasks/dirs.yml
