- name: Create .vim parent directory and plug directory
  file:
    path: /home/mbhekeni/.vim/plug
    state: directory
    recurse: yes
  when: not ansible_check_mode and not (item.stat.exists | default(false))
  register: item

- name: Test directory
  file:
    path: /home/mbhekeni/test
    state: directory
