- name: install packages
  package:
    name: 
      - htop
      - tmux
      - vim-nox
      - python3-psutil
      - dconf-cli
      - unzip
      - tar
      - google-chrome-stable 
      - git
      - kodi
      - tree
      - deluge
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
