- name: install packages
  become: true
  package:
    name: 
      - htop
      - tmux
      - vim-nox
      - python3-psutil
      - dconf-cli
      - unzip
      - tar
      - git
      - kodi
      - tree
      - deluge
      - docker
      - docker.io
      - docker-compose
      - docker-registry
      - neomutt
      - golang-go
    state: latest
    update_cache: true
